service:
  name: capstone-project-serverless-christ

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-plugin-canary-deployments
  - serverless-plugin-tracing

provider:
  tracing:
    lambda: true
    apiGateway: true
  
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

  environment:
    IMAGES_TABLE: serverless-image-table-${self:provider.stage}
    INDEX_ID_NAME: ImageIdIndex
    INDEX_UI_CD_NAME: ImageUserIdCreatedDateIndex
    S3_BUCKET: serverless-image-attachments-christ-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    AUTH0_SECRET_ID: PFYvskCLc9qfkxG_UA3LZXDpKS0wEOVRetaHYFTi84db-AuvsDZl1nHNtADBmWPL
    IMAGES_S3_BUCKET: resize-images-christdev-${self:provider.stage}
    THUMBNAILS_S3_BUCKET: resize-thumbnails-christdev-${self:provider.stage}
    SNS_ARN_CREATE:
      Fn::Join:
              - ':'
              - - arn:aws:sns
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - imageCreateTopic-${self:provider.stage}
    IMAGE_CREATE_TOPIC: imageCreateTopic-${self:provider.stage}
    SNS_ARN_WATERMARK:
      Fn::Join:
              - ':'
              - - arn:aws:sns
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - imageWatermarkTopic-${self:provider.stage}
    IMAGE_WATERMARK_TOPIC: imageWatermarkTopic-${self:provider.stage}
    SNS_ARN_DELETE:
      Fn::Join:
              - ':'
              - - arn:aws:sns
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - imageDeleteTopic-${self:provider.stage}
    IMAGE_DELETE_TOPIC: imageDeleteTopic-${self:provider.stage}


custom:
  dynamodb:
    start:
      inMemory: true
      migrate: true
    stages:
      - dev

  documentation:
    api:
      info:
        version: v1.0.0
        title: Todo API
        description: Serverless application for uploading and watermarking images
    models:
      - name: CreateImageRequest
        contentType: application/json
        schema: ${file(models/create-image-request.json)}

functions:

  RS256Auth:
    handler: src/lambda/auth/rs256Auth0Authorizer.handler
  
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # Create Image
  CreateImage:
    handler: src/lambda/http/createImage.handler
    events:
      - http:
          method: post
          path: image
          authorizer: RS256Auth
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new image process request
            description: Create a new image process request
            requestModels:
              'application/json': CreateImageRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
        Resource:
          - "*"
      - Effect: Allow
        Action:
          - es:*
        Resource: "*"
      - Effect: Allow
        Action:
          - sns:Publish
          - sns:Subscribe
        Resource:
          - "*"  

  # Get Images
  GetImages:
    handler: src/lambda/http/getImages.handler
    events:
      - http:
          method: get
          path: images
          authorizer: RS256Auth
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
        Resource:
          - "*"

  # Delete Image
  DeleteImage:
    handler: src/lambda/http/deleteImage.handler
    events:
      - http:
          method: delete
          path: image/{imageId}
          authorizer: Auth
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
        Resource:
          - "*"
      - Effect: Allow
        Action:
          - es:*
        Resource: "*"
      - Effect: Allow
        Action:
          - sns:Publish
          - sns:Subscribe
        Resource:
          - "*"

  # Generate Upload URL
  GenerateUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: image/{imageId}/file
          authorizer: Auth
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
          - s3:PutObjectTagging
        Resource: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
        Resource:
          - "*"

  ImageWatermark:
    handler: src/lambda/s3/watermarkImage.handler
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - arn:aws:sns
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - ${self:custom.topicName}
          topicName: ${self:custom.topicName}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
        Resource:
          - "*"
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
          - s3:PutObjectTagging
          - s3:GetObjectTagging
        Resource: arn:aws:s3:::${self:provider.environment.THUMBNAILS_S3_BUCKET}/*

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'*'"

        ResponseType: DEFAULT_4XX
        RestApiId: 
          Ref: 'ApiGatewayRestApi'
          
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
    
     # Table for saving images in db
    ImagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdDate
            AttributeType: S
          - AttributeName: uploadUrl
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.IMAGES_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_UI_CD_NAME}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdDate
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_ID_NAME}
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: uploadUrl
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    # Bucket for saving uploaded images
    ImagesBucket: # == AttachmentBucket
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.IMAGES_S3_BUCKET}
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:Put
              Topic: !Ref ImageTopic
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
              
    # Bucket Policy for uploading Images
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: Policy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadWriteBucketPolicy
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*
        Bucket: !Ref ImagesBucket

    
    CreateSNSTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: "*"
              Action: sns:Publish
              Resource:
                !Ref ImageTopic
              Condition:
                ArnLike:
                  AWS:SourceArn: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}
        Topics:
          - !Ref ImageTopic

    ResizedBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.THUMBNAILS_S3_BUCKET}
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:Put
              Topic: !Ref ImageResizedTopic
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    ResizedBucketPolicy: # Bucket with resized and watermarked images
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: Policy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadWriteBucketPolicy
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: arn:aws:s3:::${self:provider.environment.THUMBNAILS_S3_BUCKET}/*
        Bucket: !Ref ResizedBucket

    UpdateSNSTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: "*"
              Action: sns:Publish
              Resource:
                !Ref ImageResizedTopic
              Condition:
                ArnLike:
                  AWS:SourceArn: arn:aws:s3:::${self:provider.environment.THUMBNAILS_S3_BUCKET}
        Topics:
          - !Ref ImageResizedTopic
    